import numpy as np
import cv2
def rescaleFrame(frame,scale=0.5):
    width=int(frame.shape[1]*scale)
    height=int(frame.shape[0]*scale)
    dimensions=(width,height)
    return cv2.resize(frame,dimensions,interpolation=cv2.INTER_AREA)
image=cv2.imread('Neha.jpeg')
resized_image=rescaleFrame(image)
cv2.imshow('Coloured',resized_image)
gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
cv2.imshow('GrayScale',gray)
(thresh, BnW_image) = cv2.threshold(gray, 125, 255, cv2.THRESH_BINARY)
cv2.imshow('Black_and_White',BnW_image)
cv2.waitKey(0)
# gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
# blur=cv2.GaussianBlur(resized_image,(7,7),cv2.BORDER_DEFAULT)
# cv2.imshow('Blur',blur)
# canny=cv2.Canny(resized_image,125,175)
# cv2.imshow('Canny Edges',canny)
# dilated=cv2.dilate(canny,(100,100),iterations=3)
# cv2.imshow('Dilated',dilated)
# eroded=cv2.erode(dilated,(3,3),iterations=1)
# cv2.imshow('Eroded',eroded)