import cv2
def rescaleFrame(frame,scale=0.1):
    width=int(frame.shape[1]*scale)
    height=int(frame.shape[0]*scale)
    dimensions=(width,height)
    return cv2.resize(frame,dimensions,interpolation=cv2.INTER_AREA)
img=cv2.imread("Itachi.PNG")
resized=rescaleFrame(img)
cv2.imshow("Normal",resized)
# blur=cv2.blur(resized,(7,7))
# cv2.imshow("Blur",blur)
# guassian=cv2.GaussianBlur(resized,(7,7),0)
# cv2.imshow("Guassian Blur",guassian)
# median=cv2.medianBlur(resized,7)
# cv2.imshow("Median Blur",median)
bilateral=cv2.bilateralFilter(resized,15,30,50)
cv2.imshow("Bilateral",bilateral)
# real=cv2.cvtColor(resized,cv2.COLOR_HSV2BGR)
# cv2.imshow("real",real)
cv2.waitKey(0)